services:
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - path: .env

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - VITE_BASE_URL=http://15.236.35.167:5000/api
    depends_on:
      - back
