"""empty message

Revision ID: 08ab6fad22b8
Revises: 5d1ec21c476d
Create Date: 2025-02-18 14:14:13.768051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ab6fad22b8'
down_revision = '5d1ec21c476d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
