"""request model changes idle added

Revision ID: 7a2b404be0ab
Revises: a972a326824c
Create Date: 2025-02-21 09:30:22.204863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a2b404be0ab'
down_revision = 'a972a326824c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.ENUM('new', 'pending', 'on-processing', 'done'), nullable=False))

    # ### end Alembic commands ###
