"""empty message

Revision ID: 8c02a49eaccb
Revises: 921f0057a75e
Create Date: 2025-02-18 13:35:22.216195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c02a49eaccb'
down_revision = '921f0057a75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
