"""Ajout de la colonne picture à Car

Revision ID: 921f0057a75e
Revises: 9abde702edf2
Create Date: 2025-02-14 16:04:46.909836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921f0057a75e'
down_revision = '9abde702edf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engine', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('transmission', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('horsepower', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('topSpeed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('topSpeed')
        batch_op.drop_column('horsepower')
        batch_op.drop_column('transmission')
        batch_op.drop_column('engine')

    # ### end Alembic commands ###
