"""request status

Revision ID: a115a3a1231e
Revises: 921a23167a85
Create Date: 2025-02-18 18:12:34.614663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a115a3a1231e'
down_revision = '921a23167a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('new', 'pending', 'on-processing', 'done'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
