"""request model changes

Revision ID: a972a326824c
Revises: 5d1ffd842c9e
Create Date: 2025-02-21 09:19:33.914046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a972a326824c'
down_revision = '5d1ffd842c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('new', 'pending', 'on-processing', 'done'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('new', 'pending', 'on-processing', 'done'),
               nullable=True)

    # ### end Alembic commands ###
