"""request model changes status added again

Revision ID: f76b73f927ab
Revises: 7a2b404be0ab
Create Date: 2025-02-21 09:30:55.895020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76b73f927ab'
down_revision = '7a2b404be0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('new', 'pending', 'on-processing', 'rejected', 'accepted'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
